<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520065057 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE versification_map_id_seq CASCADE');
        $this->addSql('ALTER TABLE versification_map DROP CONSTRAINT versification_map_book_id_fkey');
        $this->addSql('DROP TABLE versification_map');
        $this->addSql('DROP INDEX books_usfm_code_key');
        $this->addSql('ALTER TABLE books ALTER usfm_code TYPE VARCHAR(3)');
        $this->addSql('ALTER TABLE books ALTER testament TYPE VARCHAR(2)');
        $this->addSql('DROP INDEX idx_gw_strongs');
        $this->addSql('DROP INDEX idx_gw_ref');
        $this->addSql('ALTER TABLE greek_words ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE greek_words ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE greek_words ALTER transliteration SET NOT NULL');
        $this->addSql('ALTER INDEX greek_words_book_id_chapter_verse_word_position_key RENAME TO gw_ref_unique');
        $this->addSql('DROP INDEX idx_hw_strongs');
        $this->addSql('DROP INDEX idx_hw_ref');
        $this->addSql('ALTER TABLE hebrew_words ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE hebrew_words ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE hebrew_words ALTER is_ketiv DROP DEFAULT');
        $this->addSql('ALTER TABLE hebrew_words ALTER has_qere DROP DEFAULT');
        $this->addSql('ALTER INDEX hebrew_words_book_id_chapter_verse_word_position_key RENAME TO hw_ref_unique');
        $this->addSql('ALTER TABLE link_confidence ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE link_confidence ALTER created_at DROP DEFAULT');
        $this->addSql('DROP INDEX idx_tv_ref');
        $this->addSql('ALTER TABLE translation_verses ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE translation_verses ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX translation_verses_translation_id_book_id_chapter_verse_key RENAME TO tv_ref_unique');
        $this->addSql('ALTER TABLE translation_words ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE translation_words ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_tw_verse RENAME TO IDX_168D76E3BBF309FA');
        $this->addSql('ALTER INDEX translation_words_verse_id_word_position_key RENAME TO tw_pos_unique');
        $this->addSql('ALTER TABLE translations ALTER language TYPE VARCHAR(3)');
        $this->addSql('ALTER TABLE translations ALTER direction DROP DEFAULT');
        $this->addSql('ALTER INDEX translations_code_key RENAME TO UNIQ_C6B7DA8777153098');
        $this->addSql('ALTER TABLE word_links ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE word_links ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE word_links ALTER source_language TYPE VARCHAR(2)');
        $this->addSql('ALTER INDEX idx_wl_he RENAME TO IDX_F31AADE4EF58481');
        $this->addSql('ALTER INDEX idx_wl_gr RENAME TO IDX_F31AADE8EC31241');
        $this->addSql('ALTER INDEX idx_wl_tw RENAME TO IDX_F31AADE425BBA7F');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE versification_map_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE versification_map (id INT DEFAULT nextval(\'versification_map_id_seq\'::regclass) NOT NULL, tradition VARCHAR(20) NOT NULL, book_id SMALLINT NOT NULL, chapter_from SMALLINT NOT NULL, verse_from SMALLINT NOT NULL, chapter_to SMALLINT NOT NULL, verse_to SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_73ED302116A2B381 ON versification_map (book_id)');
        $this->addSql('ALTER TABLE versification_map ADD CONSTRAINT versification_map_book_id_fkey FOREIGN KEY (book_id) REFERENCES books (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE books ALTER usfm_code TYPE CHAR(3)');
        $this->addSql('ALTER TABLE books ALTER testament TYPE CHAR(2)');
        $this->addSql('CREATE UNIQUE INDEX books_usfm_code_key ON books (usfm_code)');
        $this->addSql('ALTER TABLE greek_words ALTER id SET DEFAULT nextval(\'greek_words_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE greek_words ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE greek_words ALTER transliteration DROP NOT NULL');
        $this->addSql('CREATE INDEX idx_gw_strongs ON greek_words (strongs)');
        $this->addSql('CREATE INDEX idx_gw_ref ON greek_words (book_id, chapter, verse)');
        $this->addSql('ALTER INDEX gw_ref_unique RENAME TO greek_words_book_id_chapter_verse_word_position_key');
        $this->addSql('ALTER TABLE hebrew_words ALTER id SET DEFAULT nextval(\'hebrew_words_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE hebrew_words ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE hebrew_words ALTER is_ketiv SET DEFAULT false');
        $this->addSql('ALTER TABLE hebrew_words ALTER has_qere SET DEFAULT false');
        $this->addSql('CREATE INDEX idx_hw_strongs ON hebrew_words (strongs)');
        $this->addSql('CREATE INDEX idx_hw_ref ON hebrew_words (book_id, chapter, verse)');
        $this->addSql('ALTER INDEX hw_ref_unique RENAME TO hebrew_words_book_id_chapter_verse_word_position_key');
        $this->addSql('ALTER TABLE link_confidence ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE link_confidence ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE translation_verses ALTER id SET DEFAULT nextval(\'translation_verses_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE translation_verses ALTER id DROP IDENTITY');
        $this->addSql('CREATE INDEX idx_tv_ref ON translation_verses (translation_id, book_id, chapter, verse)');
        $this->addSql('ALTER INDEX tv_ref_unique RENAME TO translation_verses_translation_id_book_id_chapter_verse_key');
        $this->addSql('ALTER TABLE translation_words ALTER id SET DEFAULT nextval(\'translation_words_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE translation_words ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX idx_168d76e3bbf309fa RENAME TO idx_tw_verse');
        $this->addSql('ALTER INDEX tw_pos_unique RENAME TO translation_words_verse_id_word_position_key');
        $this->addSql('ALTER TABLE translations ALTER language TYPE CHAR(3)');
        $this->addSql('ALTER TABLE translations ALTER direction SET DEFAULT \'LTR\'');
        $this->addSql('ALTER INDEX uniq_c6b7da8777153098 RENAME TO translations_code_key');
        $this->addSql('ALTER TABLE word_links ALTER id SET DEFAULT nextval(\'word_links_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE word_links ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE word_links ALTER source_language TYPE CHAR(2)');
        $this->addSql('ALTER INDEX idx_f31aade4ef58481 RENAME TO idx_wl_he');
        $this->addSql('ALTER INDEX idx_f31aade8ec31241 RENAME TO idx_wl_gr');
        $this->addSql('ALTER INDEX idx_f31aade425bba7f RENAME TO idx_wl_tw');
    }
}
