<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the `users` table backing App\Entity\User. This table existed in
 * production but was never captured by a migration, so fresh databases
 * bootstrapped from db/schema.sql + migrations had no way to create it.
 */
final class Version20260623000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create users table (backing App\Entity\User)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE users (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            email VARCHAR(180) NOT NULL,
            display_name VARCHAR(100) NOT NULL,
            roles JSON NOT NULL,
            password VARCHAR(255) NOT NULL,
            is_verified BOOLEAN NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX users_email_unique ON users (email)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE users');
    }
}
