<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Commentary editing, next to the modern-spelling rules (Version20260928150000):
 *
 *  - spelling_rule: several word rules for the same old form ("gelijk" ->
 *    "zoals" / "net als"); the one with is_default applies everywhere, the
 *    others are alternatives. Unique now per (layer, kind, source, target).
 *  - spelling_choice: at one spot -- the n-th occurrence of an old form in
 *    one segment's Dutch text -- another of those rules (rule_id), or Los's
 *    own form (rule_id NULL).
 *  - text_flag: a problem in the text of a segment (a stray punctuation mark,
 *    an OCR error, ...), in the Latin ('la'), Los ('los') or the modern-
 *    spelling ('modern') column: the flagged text with some context around it
 *    (so it can be found again when the text is re-parsed), a category and a
 *    note, open or resolved -- a reference list for fixing the ingest.
 */
final class Version20260929090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Spelling rule alternatives + per-spot choices (spelling_choice), text flags (text_flag)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE spelling_rule ADD is_default BOOLEAN NOT NULL DEFAULT TRUE');
        $this->addSql('DROP INDEX uniq_spelling_rule_source');
        $this->addSql('CREATE UNIQUE INDEX uniq_spelling_rule_source ON spelling_rule (layer, kind, source, target)');

        $this->addSql("CREATE TABLE spelling_choice (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            layer VARCHAR(50) NOT NULL DEFAULT 'los1900',
            segment_id INT NOT NULL REFERENCES segment(id) ON DELETE CASCADE,
            source TEXT NOT NULL,
            occurrence INT NOT NULL,
            rule_id INT DEFAULT NULL REFERENCES spelling_rule(id) ON DELETE CASCADE,
            created_by VARCHAR(255) DEFAULT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT now(),
            PRIMARY KEY(id)
        )");
        $this->addSql('CREATE UNIQUE INDEX uniq_spelling_choice_spot ON spelling_choice (layer, segment_id, source, occurrence)');

        $this->addSql("CREATE TABLE text_flag (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            segment_id INT NOT NULL REFERENCES segment(id) ON DELETE CASCADE,
            field VARCHAR(10) NOT NULL CHECK (field IN ('la', 'los', 'modern')),
            snippet TEXT NOT NULL,
            context_before TEXT NOT NULL DEFAULT '',
            context_after TEXT NOT NULL DEFAULT '',
            category VARCHAR(30) NOT NULL,
            note TEXT DEFAULT NULL,
            status VARCHAR(10) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved')),
            created_by VARCHAR(255) DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT now(),
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT now(),
            resolved_by VARCHAR(255) DEFAULT NULL,
            resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY(id)
        )");
        $this->addSql('CREATE INDEX idx_text_flag_segment ON text_flag (segment_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE text_flag');
        $this->addSql('DROP TABLE spelling_choice');
        $this->addSql('DROP INDEX uniq_spelling_rule_source');
        $this->addSql('CREATE UNIQUE INDEX uniq_spelling_rule_source ON spelling_rule (layer, kind, source)');
        $this->addSql('ALTER TABLE spelling_rule DROP is_default');
    }
}
