<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates spelling_rule: the rules that turn a historical Dutch translation
 * (Los 1900, layer 'los1900') into modern spelling on the fly -- see
 * App\Service\SpellingRules. A 'word' rule replaces a whole word or phrase
 * ("beteekent" -> "betekent", "gelijk als" -> "zoals"); a 'pattern' rule
 * changes part of every word that matches ("*sch" -> "*s": mensch -> mens),
 * except the words listed in exceptions (one per line).
 */
final class Version20260928150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create spelling_rule (modern spelling of the Los translation)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE spelling_rule (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            layer VARCHAR(50) NOT NULL DEFAULT 'los1900',
            kind VARCHAR(10) NOT NULL CHECK (kind IN ('word', 'pattern')),
            source TEXT NOT NULL,
            target TEXT NOT NULL,
            exceptions TEXT NOT NULL DEFAULT '',
            position INT NOT NULL DEFAULT 0,
            active BOOLEAN NOT NULL DEFAULT TRUE,
            note TEXT DEFAULT NULL,
            created_by VARCHAR(255) DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT now(),
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT now(),
            PRIMARY KEY(id)
        )");
        $this->addSql('CREATE UNIQUE INDEX uniq_spelling_rule_source ON spelling_rule (layer, kind, lower(source))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE spelling_rule');
    }
}
