<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the push_subscriptions and news_digests tables backing the
 * Web Push notification feature (docs/push-notifications-plan.md).
 */
final class Version20260906090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create push_subscriptions and news_digests tables (Web Push notifications)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE push_subscriptions (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            endpoint TEXT NOT NULL,
            p256dh_key VARCHAR(255) NOT NULL,
            auth_key VARCHAR(255) NOT NULL,
            user_agent VARCHAR(255) DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            last_failure_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_push_subscription_user_endpoint ON push_subscriptions (user_id, endpoint)');

        $this->addSql('CREATE TABLE news_digests (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            idempotency_key VARCHAR(32) NOT NULL,
            title VARCHAR(255) NOT NULL,
            body TEXT NOT NULL,
            url VARCHAR(255) DEFAULT NULL,
            sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            success_count INT NOT NULL DEFAULT 0,
            failure_count INT NOT NULL DEFAULT 0,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX news_digests_idempotency_key_unique ON news_digests (idempotency_key)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE news_digests');
        $this->addSql('DROP TABLE push_subscriptions');
    }
}
